language: node_js
node_js:
  - "7"

script: npm run test:ci && npm run build:ci

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: travis-ci

env:
 global:
 - GH_REF: github.com/yuliatsareva/github-api-demo.git
 - secure: L5FUm7bDv7r9cKteYlaoPwY5NUWMISKvcgbT7U3t5bScBf6SaZ3V181C0X0bgDTgHQhzjL7Np5DZiiKkGRNFqipisiFLZVg4/TkJSd/tO+BrhDQss1f1eC2IL6iH1ytQTi5BLZxK5bFfMb/bYFEV4/eNc3jsOrufju1F0OBvkkijTfY7OSs1tB793wq//eOMebOjC8OASnuLsO9h7UpHU3wqvucUpsxUl4ClGHSTVzW1q7ZfUvhBXWp5P4sVK6aBPfdTz5CBOnSJB3vIM6w/BRw3+rHS2LCRPf0qGqKkXScd4PvnkjZi839mNZqQR2O/GJ3qyuYn3uYz+Inm996757ToqbMALmqNOD0MOlr/4hGnyZ11dyFYczuF9U/7EVDE/s0NGndX7+yUSt1oH1tAjWPQj9dDLjsY80RXORMUpygEMNp+dAlsG8k9gVb7TbehBA1MEV4fC7Z0NNqIinL7mD5fbdgg/t2j90HUiDv7j7OyOQVPiYKiORepeVfPacxJQ2G4xKorBWbLFmgl/SlzrzpU07yLrg2HTpImg2KuBvpf1c1VoNjKzwWaq4G/msuY3rdZCN4OjyjDVHGgI18N1lkSGZ1AyJQbBddIROv952Tjw3I4Xv40Cm9UXFrP0L/JqJnEc7Q/fPKjWLHz5ZAQrwD+qTvubA7Z4FYIMiAOhHw=
